## This file is a general .xdc for the Basys3 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

## Switches (16)
set_property PACKAGE_PIN V17 [get_ports {swt[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[0]}]
set_property PACKAGE_PIN V16 [get_ports {swt[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[1]}]
set_property PACKAGE_PIN W16 [get_ports {swt[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[2]}]
set_property PACKAGE_PIN W17 [get_ports {swt[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[3]}]
set_property PACKAGE_PIN W15 [get_ports {swt[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[4]}]
set_property PACKAGE_PIN V15 [get_ports {swt[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[5]}]
set_property PACKAGE_PIN W14 [get_ports {swt[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[6]}]
set_property PACKAGE_PIN W13 [get_ports {swt[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[7]}]
set_property PACKAGE_PIN V2 [get_ports {swt[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[8]}]
set_property PACKAGE_PIN T3 [get_ports {swt[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[9]}]
set_property PACKAGE_PIN T2 [get_ports {swt[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[10]}]
set_property PACKAGE_PIN R3 [get_ports {swt[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[11]}]
set_property PACKAGE_PIN W2 [get_ports {swt[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[12]}]
set_property PACKAGE_PIN U1 [get_ports {swt[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[13]}]
set_property PACKAGE_PIN T1 [get_ports {swt[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[14]}]
set_property PACKAGE_PIN R2 [get_ports {swt[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {swt[15]}]

## LEDs (16)
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property PACKAGE_PIN V3 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property PACKAGE_PIN W3 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property PACKAGE_PIN U3 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property PACKAGE_PIN P3 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property PACKAGE_PIN N3 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property PACKAGE_PIN P1 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property PACKAGE_PIN L1 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]

## 7 segment display
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]

set_property PACKAGE_PIN V7 [get_ports dp]
set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN U2 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]

## Buttons
set_property PACKAGE_PIN U18 [get_ports btn_reset]
set_property IOSTANDARD LVCMOS33 [get_ports btn_reset]
set_property PACKAGE_PIN T18 [get_ports btn_clk]
set_property IOSTANDARD LVCMOS33 [get_ports btn_clk]

## Pmod Header JA (Pmod KYPD - Teclado Matricial)
## Filas (Salidas)
set_property PACKAGE_PIN J1 [get_ports {keypad_row[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_row[0]}]
set_property PACKAGE_PIN L2 [get_ports {keypad_row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_row[1]}]
set_property PACKAGE_PIN J2 [get_ports {keypad_row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_row[2]}]
set_property PACKAGE_PIN G2 [get_ports {keypad_row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_row[3]}]

## Columnas (Entradas con Pull-Up activado)
set_property PACKAGE_PIN H1 [get_ports {keypad_col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_col[0]}]
set_property PULLUP true [get_ports {keypad_col[0]}]
set_property PACKAGE_PIN K2 [get_ports {keypad_col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_col[1]}]
set_property PULLUP true [get_ports {keypad_col[1]}]
set_property PACKAGE_PIN H2 [get_ports {keypad_col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_col[2]}]
set_property PULLUP true [get_ports {keypad_col[2]}]
set_property PACKAGE_PIN G3 [get_ports {keypad_col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keypad_col[3]}]
set_property PULLUP true [get_ports {keypad_col[3]}]

## Pmod Header JB (Pmod OLED SPI)
## Fila Superior (Pines 1 a 4)
set_property PACKAGE_PIN A14 [get_ports oled_cs]
set_property IOSTANDARD LVCMOS33 [get_ports oled_cs]
set_property PACKAGE_PIN A16 [get_ports oled_sdin]
set_property IOSTANDARD LVCMOS33 [get_ports oled_sdin]
## El pin 3 del Pmod es MISO, pero el módulo no lo usa para devolver datos
set_property PACKAGE_PIN B16 [get_ports oled_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports oled_sclk]

## Fila Inferior (Pines 7 a 10)
set_property PACKAGE_PIN A15 [get_ports oled_dc]
set_property IOSTANDARD LVCMOS33 [get_ports oled_dc]
set_property PACKAGE_PIN A17 [get_ports oled_res]
set_property IOSTANDARD LVCMOS33 [get_ports oled_res]
set_property PACKAGE_PIN C15 [get_ports oled_vbat]
set_property IOSTANDARD LVCMOS33 [get_ports oled_vbat]
set_property PACKAGE_PIN C16 [get_ports oled_vdd]
set_property IOSTANDARD LVCMOS33 [get_ports oled_vdd]